#!/usr/bin/env bash
set -e

export HY3D_SERVER_WORKSPACE_ROOT="${HY3D_SERVER_WORKSPACE_ROOT:-/app/server_workspace}"
export HY3D_SERVER_EXPORTS_ROOT="${HY3D_SERVER_EXPORTS_ROOT:-/app/server_exports}"
export HY3D_MODEL_CACHE="${HY3D_MODEL_CACHE:-/app/model_cache}"

mkdir -p "$HY3D_SERVER_WORKSPACE_ROOT" "$HY3D_SERVER_EXPORTS_ROOT" "$HY3D_MODEL_CACHE"

echo "HY3D API configuration:"
echo "  HY3D_SERVER_WORKSPACE_ROOT=${HY3D_SERVER_WORKSPACE_ROOT}"
echo "  HY3D_SERVER_EXPORTS_ROOT=${HY3D_SERVER_EXPORTS_ROOT}"
echo "  HY3D_ENGINE_ROOT=${HY3D_ENGINE_ROOT:-}"
echo "  HY3D_WRAPPER_RUN=${HY3D_WRAPPER_RUN:-}"
echo "  HY3D_SERVER_FIXTURE_RESULT_PACKAGE=${HY3D_SERVER_FIXTURE_RESULT_PACKAGE:-}"
echo "  HY3D_MODEL_CACHE=${HY3D_MODEL_CACHE}"

exec "$@"

